### ISSUE TITLE
如何禁止swiper的手势滑动操作，只让其轮播？

### ISSUE THREAD

**Issue by CCY0122** [best-flutter/flutter_swiper#109]
作者你好。请问如何让Swiper不接受触摸滑动，而只能轮播？就行安卓原生上ViewFlipper那样

**Comment by CCY0122** [comment]
我想补充下我的问题：我想禁用掉Swiper的滑动事件，但是点击事件还是想要保留，所以直接给Swiper套一层 `IgnorePointer`是不满足需求的。
这种需求还是很常见的，如一个垂直列表中含一个垂直滚动的广告轮播栏，当用户手指落点在广告栏并上下滑动时，肯定希望仍然滑动的是列表而不是广告栏，一般期望广告栏只接受点击事件的。

**Comment by CCY0122** [comment]
解决了。给Swiper使用`NeverScrollableScrollPhysics()`这个physics即可

**Comment by bianxiang** [comment]
请问自动轮播的时候如何使点击每一个item可响应？必须停下来才能点击 @CCY0122

**Comment by frankfancode** [comment]
> 请问自动轮播的时候如何使点击每一个item可响应？必须停下来才能点击 @CCY0122

有个较为麻烦的方法
计算点击时滑动的比例和点击位置在显示区域的比例，然后根据两个比例计算 点击位置应该落于哪一项。
