### ISSUE TITLE
Issue with initial index

### ISSUE THREAD

**Issue by sonathati** [best-flutter/flutter_swiper#11]
Specifying Index number of initial slide through "index" in Swiper() is not working. Everytime opens image at index = 0

**Comment by tiholic** [comment]
I too faced this issue

**Comment by jzoom** [comment]
This is very strange. Several month ago , it worked fine , just create a new PageController with a new index ,and set to the PageView, now it seems not working at all. We'll fix this issue at next version.

**Comment by tiholic** [comment]
Thanks @jzoom . When can we expect the next version to be released?
