### ISSUE TITLE
Disabling Infinite Looping feature

### ISSUE THREAD

**Issue by danausx** [best-flutter/flutter_swiper#123]
Is there any way to disable the loop feature and have it act as a standard scrolling list but just using the snap feature?

The infinite loop makes it hard to use this as anything else but very long lists. Short lists make it confusing as they loop around and items appear doubled.

**Comment by MRL-00** [comment]
You can just use `loop: false`

```Swiper(
    itemBuilder: (BuildContext context, int index) {
    return new ClipRRect(
       borderRadius: new BorderRadius.circular(10.0),
       child: Image.network(
         "http://via.placeholder.com/288x188",
          fit: BoxFit.fill,
         )
     );
},
 itemCount: 3,
 index: 0,
 viewportFraction: 1.0,
 scale: 0.9,
 loop: false,
 pagination: SwiperPagination(                   
 )
)
```

**Comment by danausx** [comment]
Oh wow, this is great. I was convinced the loop parameter was just for the automatic slideshow mode. 
This is perfect thanks!
