### ISSUE TITLE
Compatibility for flutter-web

### ISSUE THREAD

**Issue by ali-alizadeh** [best-flutter/flutter_swiper#130]
Hello.
A friend of mine has made this package compatible with flutter-web. How can he release this? Should he fork your project and make the required changes or release a new package or something else?

**Comment by MOPineyro** [comment]
@Ali-Alizadeh is the version compatible with flutter-web available anywhere on github?

Would appreciate a fork, interested in using

**Comment by ali-alizadeh** [comment]
I guess there's no need for such thing anymore cause of the major updates of flutter on the web in the last year. Closing for now.
