### ISSUE TITLE
after flutter SDK Update

### ISSUE THREAD

**Issue by zhanglijie5997** [best-flutter/flutter_swiper#168]
after flutter sdk update，flutter_swiper can't use , thanks

**Comment by thedejifab** [comment]
@zhanglijie5997 what issue particularly are you experiencing? Provide more details please

**Comment by zhanglijie5997** [comment]
update flutter sdk, my flutter sdk version is Flutter:0.0.0-unknow, when using flutter_swiper plugin,  error repord :  flutter sdk >=2.1.0 <3.0.0 , no compatible with plugin version, thanks

**Comment by zhanglijie5997** [comment]
solver， i  switched to the dev branch.
