### ISSUE TITLE
flutter_swiper: ^1.0.6里面的点击事件onTap怎么不执行啊.没反应

### ISSUE THREAD

**Issue by ZHLhenry** [best-flutter/flutter_swiper#17]
class _ClassifyPage extends State<ClassifyPage> {
  @override
  Widget build(BuildContext context) {
    return new Container(
      width: MediaQuery
          .of(context)
          .size
          .width,
      height: 200.0,
      child: new Swiper(
          itemBuilder: _swiperBuilder,
          itemCount: 2,
          pagination: new SwiperPagination(
              builder: DotSwiperPaginationBuilder(
                  color: Colors.white,
                  activeColor: Colors.red
              ),
              margin: EdgeInsets.all(30.0)
          ),
          control: new SwiperControl(
            iconNext: null,
            iconPrevious: null,
          ),
          scrollDirection: Axis.horizontal,
          autoplay: true,
          onTap: (index) => print('点击了第个')
      ),
    );
}

能帮我解答下么?

**Comment by jzoom** [comment]
最新版本修复了1.1.2

**Comment by jzoom** [comment]
目前最新版本是1.1.3
