### ISSUE TITLE
Swiper physics

### ISSUE THREAD

**Issue by yarmel** [best-flutter/flutter_swiper#185]
Hi & thank you for your great work on Swiper. I use it & I like it but can you please explain how can I use Swiper inside PageView without set physics: NeverScrollableScrollPhysics(). Default ListView scroll inside PageView fine but when I try to Swipe it change my Page. Can you help with this issue?

`Swiper(
                        layout: SwiperLayout.STACK,
                        fade: 1.0,
                        itemWidth: containerWidth,
                        itemHeight: containerHeight,
                        itemBuilder: (context, index) {
                          if (motivations.length >= 3) {
                            return LargeMotivationCard(
                              containerHeight: containerHeight,
                              containerWidth: containerWidth,
                              motivation: motivations[index],
                              index: index,
                              border: 8.0,
                            );
                          } else {
                            return Container(
                              child: Padding(
                                padding: const EdgeInsets.all(80.0),
                                child: SvgPicture.asset(
                                  'storage/assets/icons/tabs/ai.svg',
                                  color: Theme.of(context).accentColor.withOpacity(0.1),
                                ),
                              ),
                            );
                          }
                        },
                        itemCount: 7,
                      ),`

**Comment by AhmedNourJamalElDin** [comment]
Any update, please?

**Comment by yarmel** [comment]
Hi. This is not actual any more. Thanks

**Comment by AhmedNourJamalElDin** [comment]
Sorry, what do you mean?
