### ISSUE TITLE
Custom layout does not support SwiperControllerEvent.MOVE_INDEX yet!

### ISSUE THREAD

**Issue by ghost** [best-flutter/flutter_swiper#189]
why  Custom layout does not support SwiperControllerEvent.MOVE_INDEX yet!

自定义布局的swiper如何通过使用函数出发跳转到某个index

How to jump to an index by using the function when use custom swiper

**Comment by sarinupreti** [comment]
any solutions ?

**Comment by stevenosse** [comment]
May be you can try `controller.next()` and `controller.previous()` ???
