### ISSUE TITLE
Failed assertion: line 110 pos 12: '_positions.isNotEmpty'

### ISSUE THREAD

**Issue by dingzuhua** [best-flutter/flutter_swiper#198]
I have 5 pieces of data in my Swiper, I have an Index record of the current position, and when I delete the last item, I move the Index forward and delete the last item. This is when the error is reported.

flutter: The following assertion was thrown:
flutter: ScrollController not attached to any scroll views.
flutter: 'package:flutter/src/widgets/scroll_controller.dart':
flutter: Failed assertion: line 110 pos 12: '_positions.isNotEmpty'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.

**Comment by dingzuhua** [comment]
As a test, swiperlayout. DEFAULT appears when layout is selected

**Comment by weiminghuaa** [comment]
I only can use DEFAULT layout. This bug should be fixed, please do it.

**Comment by weiminghuaa** [comment]
If don't set index, it's ok!

**Comment by weiminghuaa** [comment]
```
        Swiper(
            loop: false,
            itemBuilder: (BuildContext context, int index) {
              return Center(
                  child: Image.file(
                _imageList[index],
                fit: BoxFit.fill,
              ));
            },
            itemCount: _imageList.length,
            index: _index == widget.initialIndex ? _index : null,
            onIndexChanged: (index) {
              setState(() {
                _index = index;
              });
            },
         )
```

**Comment by amit-rawal** [comment]
>         Swiper(
>             loop: false,
>             itemBuilder: (BuildContext context, int index) {
>               return Center(
>                   child: Image.file(
>                 _imageList[index],
>                 fit: BoxFit.fill,
>               ));
>             },
>             itemCount: _imageList.length,
>             index: _index == widget.initialIndex ? _index : null,
>             onIndexChanged: (index) {
>               setState(() {
>                 _index = index;
>               });
>             },
>          )

Working , thanks brother
