### ISSUE TITLE
How to have Swiper automatically adapt to his items ?

### ISSUE THREAD

**Issue by Yirmeyah-d** [best-flutter/flutter_swiper#201]
I want Swiper to adapt to his items height and auto-resize.
Here my code:
Swiper(
                itemBuilder: (BuildContext context, int index) {
                  return savedPostItems[index];
                },
                itemCount: savedPostItems.length,
                viewportFraction: 0.8,
                scale: 0.9,
                loop: false,
                itemWidth: 450,
                itemHeight: 300,
                layout: SwiperLayout.TINDER,
              )
The items in it are container.
Thank you in advance,

**Comment by ahmadkhedr** [comment]
> I want Swiper to adapt to his items height and auto-resize.
> Here my code:
> Swiper(
> itemBuilder: (BuildContext context, int index) {
> return savedPostItems[index];
> },
> itemCount: savedPostItems.length,
> viewportFraction: 0.8,
> scale: 0.9,
> loop: false,
> itemWidth: 450,
> itemHeight: 300,
> layout: SwiperLayout.TINDER,
> )
> The items in it are container.
> Thank you in advance,

have you reached the solution?

**Comment by Yirmeyah-d** [comment]
Yes i have but it wasn't really the answer to this questions.
I foud a way to solve my issue without havig to adapt Swiper automatically to his item
