### ISSUE TITLE
怎样一行展示多个item

### ISSUE THREAD

**Issue by Small-World** [best-flutter/flutter_swiper#213]
我想要一行展示多个item，可以适配吗，或者可以怎样自定义

**Comment by wangxingxing123654** [comment]
> 我想要一行展示多个item，可以适配吗，或者可以怎样自定义

怎么关了呀？同问@Small-World

**Comment by Small-World** [comment]
> > 我想要一行展示多个item，可以适配吗，或者可以怎样自定义
> 
> 怎么关了呀？同问@Small-World

试试参数“viewportFraction”和“scale”
例如：
viewportFraction: 0.8,
                  scale: 0.9,
