### ISSUE TITLE
flutter_swiper and tabBar, error message：setState() called after dispose(); lifecycle state defunct not mounted

### ISSUE THREAD

**Issue by ghost** [best-flutter/flutter_swiper#220]
是tabBar中组件嵌套flutter_swiper,在切换tabBarView后，报错： setState() called after dispose(); lifecycle state defunct not mounted

![微信截图_20200818122941](https://user-images.githubusercontent.com/31248269/90471930-f22f2d00-e151-11ea-99e0-2dc5705ac302.png)

![微信截图_20200818081940](https://user-images.githubusercontent.com/31248269/90471999-12f78280-e152-11ea-8997-549a0d059bd0.png)

我只是在每个tabBarView里面加入了swiper

`class SwiperCard extends StatefulWidget {
  List _data = <NavInfoSchemaValueSwiperList>[];
  SwiperCard(this._data, {Key key}) : super(key: key);

  @override
  _SwiperCardState createState() => _SwiperCardState(_data);
}

class _SwiperCardState extends State<SwiperCard> {
  List _data = <NavInfoSchemaValueSwiperList>[];
  _SwiperCardState(this._data);

  @override
  Widget build(BuildContext context) {
    return _data.length > 0
        ? Container(
            height: 160,
            child: new Swiper(
              itemBuilder: (BuildContext context, int index) {
                return new Image.network(
                  _data[index].poster,
                  fit: BoxFit.fill,
                  height: 160,
                );
              },
              onTap: (index) {
                // query
                Map args = <String, String>{'_id': _data[index].Id};
                // router push
                Navigator.pushNamed(context, '/video', arguments: args);
              },
              itemCount: _data.length,
              pagination: new SwiperPagination(),
            ),
          )
        : Container();
  }
}`

**Comment by abcd498936590** [comment]
![微信截图_20200818081940](https://user-images.githubusercontent.com/31248269/90471972-04a96680-e152-11ea-9e02-ee310d4ff818.png)

**Comment by YouSour** [comment]
@abcd498936590 you can fix this error ?

**Comment by ghost** [comment]
> @abcd498936590 you can fix this error ?

if (mounted){

}

**Comment by abcd498936590** [comment]
> @abcd498936590你可以修复这个错误？

https://github.com/abcd498936590/Dart-Cms-Flutter/blob/master/lib/views/home/appBar/home.dart     You can refer to （row 219）

**Comment by YouSour** [comment]
where should i add that line ? around swiper widget ? @abcd498936590

**Comment by ghost** [comment]
> where should i add that line ? around swiper widget ? @abcd498936590

The place where the variable is changed, for example, to get the result of an ajax request, you will change the variable so that the view is updated, this is it 

You can refer to my project   （line  160）
https://github.com/abcd498936590/Dart-Cms-Flutter/blob/master/lib/views/home/appBar/home.dart

**Comment by YouSour** [comment]
@abcd498936590 how can i use that line in provider ? the way you write and my code are different

**Comment by YouSour** [comment]
here what my code look like : 
```
class SaleOrderProvider with ChangeNotifier {
  List<ProductSaleOrderModel> _productPopular = [];
  List<ProductSaleOrderModel> get productPopular => [..._productPopular];
  
   void getProductPopular() async {
    _departmentDoc = await DepartmentStorage().getUserDepartment();
    _branchDoc = await BranchStorage().getUserBranches();
    String _ipAddress = await ConnectionStorage().getIpAddress();
    //set params
    final Map<String, dynamic> _params = {
      'status': 'Active',
      'favorite': true,
    };

    // Set Options
    final _options = {
      'sort': {'name': 1},
    };

    final Map<String, dynamic> _tempProductsData =
        await meteor.call('rest.findProductForSale', [
      {
        'params': _params,
        'options': _options,
        'depId': _departmentDoc['_id'],
        'branchId': _branchDoc['_id'],
      }
    ]);

    if (_tempProductsData.length > 0) {
      //find image url
      List<dynamic> _productData = ImageServices()
          .findImages(items: _tempProductsData['items'], ipAddress: _ipAddress);

      //get product list
      _productPopular = _productData
          .map((newProducts) => ProductSaleOrderModel.fromJson(newProducts))
          .toList();
    }

    notifyListeners();
  }
  
}
```

**Comment by ghost** [comment]
> @abcd498936590 how can i use that line in provider ? the way you write and my code are different

Sorry, I have no experience with provider. I am ashamed

**Comment by YouSour** [comment]
@abcd498936590 that's ok , thank you for your time :smile:
