### ISSUE TITLE
Pagination position

### ISSUE THREAD

**Issue by mehmetyilmaz001** [best-flutter/flutter_swiper#252]
Hi,

I want to make pagination like this.

![image](https://user-images.githubusercontent.com/5219953/102924799-4bfa8780-44a3-11eb-986d-f5d87ec70296.png)

Bu i could not do it. It shows like this.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/5219953/102924860-66ccfc00-44a3-11eb-89a8-27ef7f5c2c36.png">

How can I fix this?

**Comment by popeyelau** [comment]
`outer: true`

**Comment by CARocha** [comment]
@popeyelau hello and I'm sorry, you know how I can know when the end of swiper is, for example, I have 5 pages when I reach the last one, tell the user I reach the end, congratulations, something like that

**Comment by popeyelau** [comment]
@CARocha
 `onIndexChanged` called with the new index when the user swiped or autoplay
