### ISSUE TITLE
Migrate to sound null safety

### ISSUE THREAD

**Issue by adarsh-technocrat** [best-flutter/flutter_swiper#256]
### **Description**

- Migrate to sound null safety
- Bump up package version

**Comment by amebrahimi** [comment]
Any updates on this?

**Comment by leynier** [comment]
I will make a PR with null safety support implementation

**Comment by sebastianbuechler** [comment]
@leynier Unfortunately, it does not look like any of the PRs are getting merged.

**Comment by higorlapacw** [comment]
@sebastianbuechler  @leynier  maybe creating a fork? `extended_flutter_swiper`

**Comment by adarsh-technocrat** [comment]
> I will make a PR with null safety support implementation

Hey, @leynier are you working on this issue?

**Comment by leynier** [comment]
> > I will make a PR with null safety support implementation
> 
> Hey, @leynier are you working on this issue?

I have not started working on the issue, but I want to do it soon.  I think for next week.

**Comment by tomirons** [comment]
@leynier since this repository is clearly inactive, I would create a new one but give credit to the original.

**Comment by higorlapacw** [comment]
Sounds good.

**Comment by SeriousMonk** [comment]
Any updates?

**Comment by leynier** [comment]
> Any updates?

A pull request (#264) was made.

**Comment by lianyagang** [comment]
> Any updates?

try use 
https://github.com/lianyagang/flutter_swiper_null_safety/tree/master solved null_safety

**Comment by lianyagang** [comment]
try use 
https://github.com/lianyagang/flutter_swiper_null_safety/tree/master solved null_safety

**Comment by TheAnkurPanchani** [comment]
I have forked this repo and merged most of PRs into it (including PR #264). You can find the package here: https://pub.dev/packages/card_swiper

**Comment by higorlapacw** [comment]
Thanks, @TheAnkurPanchani!

**Comment by lianyagang** [comment]
> Thanks, @TheAnkurPanchani!

You can try the following version

dependencies:
  flutter_swiper_null_safety: ^1.0.2

**Comment by lianyagang** [comment]
> I have forked this repo and merged most of PRs into it (including PR #264). You can find the package here: https://pub.dev/packages/card_swiper

You can try the following version

dependencies:
  flutter_swiper_null_safety: ^1.0.2
