### ISSUE TITLE
How to get rid of the white border around the image? 

### ISSUE THREAD

**Issue by sgon00** [best-flutter/flutter_swiper#30]
I put the `Swiper` inside a `Container` and my background color of the `Scaffold` is not white. So I can see a white border around the image. I am unable to get rid of the white border. Anyone have any ideas? Thanks a lot.

```dart
Container(
              height: 350,
              color: someColor,
              child: Swiper(
                itemBuilder: (BuildContext context, int index) {
                  return carouselImageList[index];
                },
                itemCount: 4,
                autoplay: true,
                autoplayDelay: 7000,
                pagination: SwiperPagination(
                  alignment: Alignment(0, 1.0),
                ),
              ),
            ),
```

**Comment by sgon00** [comment]
I think it's something to do with the `Card` widget. I wrapped this Container inside a `Card`. By removing the Card, the white border is gone. So closing this issue.

**Comment by Finn1510** [comment]
For anyone who might come across this while googling, setting the Card color to `Colors.transparent` worked for me.
