### ISSUE TITLE
How to add item image from asset

### ISSUE THREAD

**Issue by Nabouste** [best-flutter/flutter_swiper#60]
hi i want to add 4 custom image from asset.
but i dont know how to implement this.

`new Swiper(
              autoplay: true,
              itemBuilder: (BuildContext context, int index) {
                return InkWell(
                  onTap: (){
                    print("aaaaa");
                  },
                                  child: new Image.asset(
                    "img/dummy.jpg",
                    fit: BoxFit.fill,
                  ),
                );
              },
              itemCount: 4,
              viewportFraction: 0.8,
              scale: 0.9,
            ),
          ),`

the code just showing 1 image from asset.
how to show more than 1 image in this swipper ?
also an implementation using indicator ._.

thanks

**Comment by SrOptimus** [comment]
i want to know too

**Comment by DanielMenconi** [comment]
anyone?

**Comment by ghozay19** [comment]
> use this

> make list from lokal :
var gambar = "img/dummy.jpg";
  final List<String> imgList = [
    'img/dummy.jpg',
    'img/1.jpg',
    'img/2.jpg',
    'img/3.jpg',
    'img/4.jpg',
  ];

> Call them on swiper
Swiper(
              viewportFraction: 0.8,
              scale: 0.9,
              autoplay: true,
              itemCount: imgList.length,
              itemBuilder: (BuildContext context, int index) {
                return InkWell(
                  onTap: () {
                    switch (index) {
                      case 0:
                        print('gambar 0');
                        break;
                      case 1:
                        print('gambar 1');
                        break;
                      case 2:
                        print('gambar 2');
                        break;
                      case 3:
                        print('gambar 3');
                        break;
                      case 4:
                        print('gambar 4');
                        break;
                    }
                  },
                  child: Image.asset(
                    imgList[index],
                    fit: BoxFit.fitWidth,
                  ),
                );
              },
              pagination: SwiperPagination(),
            ),
          ),


sorry for bad code.
