### ISSUE TITLE
How do I change SwiperPagination.dots color?

### ISSUE THREAD

**Issue by NTMS2017** [best-flutter/flutter_swiper#78]
Hi,

I need to change active and none active SwiperPagination.dots color. How do I do that?

Currently active color shows green and none active color shows white. Currently I have green background and cannot see active color. It simply shows none active page color with is white.

I need to change active and none active color based on my background picture. How can I do that?

Thanks for this great plugin.

**Comment by mrgray** [comment]
@NTMS2017 Did you ever figure this one out?

**Comment by NTMS2017** [comment]
Not yet, do you know how to do it?

**Comment by lavanoped** [comment]
You have to change the package library itself. In the file, src/swiper_pagination.dart

 ```
class DotSwiperPaginationBuilder{
Widget build(BuildContext context, SwiperPluginConfig config) {
    ...
    Color activeColor = this.activeColor; //pick your color here =Colors.blueAccent
    Color color = this.color;  //pick your color here =Colors.blue
```

As far as I know. If you have to change the colors dynamically, then you might have to create added methods into Swiper or implement the whole package into your app's lib itself.

**Comment by NTMS2017** [comment]
I will check it today, and yes I need to change the color dynamically. Thanks

**Comment by NTMS2017** [comment]
Thank you very much its working

**Comment by rstrelba** [comment]
```
          pagination: new SwiperPagination(
              margin: new EdgeInsets.all(5.0),
              builder: new DotSwiperPaginationBuilder(
                  color: Colors.grey, activeColor: Colors.red)),

```
